server:
  port: 8025

spring:
  application:
    name: consul-mail
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
logging:
  level:
    indi.huishi.shizuo.controller: info
    indi.huishi.shizuo.service: warn
  file:
    name: E:\\java_exercise\\others\\distribute_shizuo\\log_mail.log

